export const DATA_LOADING = "DATA_LOADING";
export const ADD_COIN_SUCCESS = "ADD_COIN_SUCCESS";
export const CHART_DATA_SUCCESS = "CHART_DATA_SUCCESS";
export const DATA_FETCH_ERROR = "DATA_FETCH_ERROR";
export const ADD_TO_WATCH_LIST = "ADD_TO_WATCH_LIST";
export const DELETE_COIN = "DELETE_COIN";